server.port: 8085

spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:mysql://localhost:3316/order-svc?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db-user
    password: P@swr11d
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations:
      - classpath:db/migrations
    baselineVersion: 1
    baselineOnMigrate: true
---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    locations:
      - classpath:db/h2/migrations
