server.port: 8182

spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:local}
  application.name: web
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google.oauth2.clientId}
            clientSecret: ${google.oauth2.clientSecret}
logging:
  level:
    org.springframework.kafka.config: trace
thymeleaf:
  cache: false
ecommerce:
  include:
    kafka: true

---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3316/web-svc?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db-user
    password: P@swr11d
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    locations:
      - classpath:db/migrations
    baselineOnMigrate: true
    baselineVersion: 1
  kafka:
    bootstrap-servers: localhost:29092
    schema-registry-url: http://localhost:8089
---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    locations:
      - classpath:db/h2/migrations
ecommerce:
  include:
    kafka: false
